name: integration test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  k8s-test:
    name: kubernetes integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ko
        run: |
          curl -L https://github.com/google/ko/releases/download/v0.8.1/ko_0.8.1_Linux_x86_64.tar.gz | sudo tar xzf - /usr/local/bin/ko
          chmod +x /usr/local/bin/ko